# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bodgegui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.startFrameSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.startFrameSpinBox.setMaximum(0)
        self.startFrameSpinBox.setObjectName("startFrameSpinBox")
        self.gridLayout_3.addWidget(self.startFrameSpinBox, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.lengthSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.lengthSpinBox.setMaximum(0)
        self.lengthSpinBox.setObjectName("lengthSpinBox")
        self.gridLayout_3.addWidget(self.lengthSpinBox, 4, 1, 1, 1)
        self.availableFramesLabel = QtWidgets.QLabel(self.groupBox)
        self.availableFramesLabel.setObjectName("availableFramesLabel")
        self.gridLayout_3.addWidget(self.availableFramesLabel, 2, 1, 1, 1)
        self.texComboBox = QtWidgets.QComboBox(self.groupBox)
        self.texComboBox.setObjectName("texComboBox")
        self.texComboBox.addItem("")
        self.texComboBox.addItem("")
        self.texComboBox.addItem("")
        self.texComboBox.addItem("")
        self.gridLayout_3.addWidget(self.texComboBox, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 5, 0, 1, 1)
        self.pathLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.gridLayout_3.addWidget(self.pathLineEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newProgramButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.newProgramButton.setObjectName("newProgramButton")
        self.verticalLayout.addWidget(self.newProgramButton)
        self.newProgramLineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.newProgramLineEdit.setObjectName("newProgramLineEdit")
        self.verticalLayout.addWidget(self.newProgramLineEdit)
        self.programListWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.programListWidget.setObjectName("programListWidget")
        self.verticalLayout.addWidget(self.programListWidget)
        self.shaderAPath = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.shaderAPath.setObjectName("shaderAPath")
        self.verticalLayout.addWidget(self.shaderAPath)
        self.shaderBPath = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.shaderBPath.setObjectName("shaderBPath")
        self.verticalLayout.addWidget(self.shaderBPath)
        self.shaderCPath = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.shaderCPath.setObjectName("shaderCPath")
        self.verticalLayout.addWidget(self.shaderCPath)
        self.shaderDPath = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.shaderDPath.setObjectName("shaderDPath")
        self.verticalLayout.addWidget(self.shaderDPath)
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.newTextureButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.newTextureButton.setObjectName("newTextureButton")
        self.verticalLayout.addWidget(self.newTextureButton)
        self.newTextureLineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.newTextureLineEdit.setObjectName("newTextureLineEdit")
        self.verticalLayout.addWidget(self.newTextureLineEdit)
        self.textureListWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.textureListWidget.setObjectName("textureListWidget")
        self.verticalLayout.addWidget(self.textureListWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Frame Selection"))
        self.label.setText(_translate("MainWindow", "Start Frame"))
        self.label_2.setText(_translate("MainWindow", "Length"))
        self.label_3.setText(_translate("MainWindow", "Total available frames"))
        self.availableFramesLabel.setText(_translate("MainWindow", "0"))
        self.texComboBox.setItemText(0, _translate("MainWindow", "Off"))
        self.texComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.texComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.texComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.label_4.setText(_translate("MainWindow", "Texture Bank"))
        self.label_5.setText(_translate("MainWindow", "Path to Folder"))
        self.newProgramButton.setText(_translate("MainWindow", "New Program"))
        self.newProgramLineEdit.setPlaceholderText(_translate("MainWindow", "Program Name"))
        self.newTextureButton.setText(_translate("MainWindow", "New Texturestreamer"))
        self.newTextureLineEdit.setPlaceholderText(_translate("MainWindow", "Streamer Name"))

